from Stack import *
from Queue import *

def trace(obj):
	print(obj.info())


print("--------------stack----------------")

s = Stack(5)  
s.push(1)
trace(s)
s.push(2)
trace(s)  
s.push(3)
trace(s)  
s.push(4)
trace(s)  
s.push(5)  
trace(s)
print("head = ", s.head())
print("tail = ", s.tail())
print("isFull? ", s.isFull())
s.pop()  
trace(s)
s.pop()
trace(s)
s.pop()
trace(s)
s.pop()
trace(s)
s.pop()
trace(s)
print("isEmpty? ",s.isEmpty())

print("--------------quese----------------")

q = Queue(5)
q.add(1)
trace(q)
q.add(2)
trace(q)
q.add(3)
trace(q)
q.add(4)
trace(q)
q.add(5)
trace(q)
print("first = ", q.first())
print("last = ", q.last())
print("isFull? ", q.isFull())
q.remove()
trace(q)
q.remove()
trace(q)
q.remove()
trace(q)
q.remove()
trace(q)
q.remove()
trace(q)
print("isEmpty? ",s.isEmpty())